spring.application.name=climaAlert

# WeatherAPI
weather.api.key= api 
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.city= Ciudad Autonoma de Buenos Aires

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= email
spring.mail.password= contraseña de aplicacion 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true